---
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          target: x86_64-unknown-linux-musl
          toolchain: stable
      - run: "cargo build --release --target x86_64-unknown-linux-musl\ncd target/x86_64-unknown-linux-musl/release\nzip syconf-linux.zip syconf"
      - uses: actions/upload-artifact@v2
        with:
          name: linux-bin
          path: target/x86_64-unknown-linux-musl/release/syconf-linux.zip
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: "cargo build --release \ncd target/release\nzip syconf-macos.zip syconf"
      - uses: actions/upload-artifact@v2
        with:
          name: macos-bin
          path: target/release/syconf-macos.zip
  create-release:
    needs:
      - build-linux
      - build-macos
    runs-on: ubuntu-latest
    steps:
      - name: Downloads linux-bin
        uses: actions/download-artifact@v2
        with:
          name: linux-bin
      - name: Downloads macos-bin
        uses: actions/download-artifact@v2
        with:
          name: macos-bin
      - env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        id: create_release
        name: Create release
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          release_name: "Release ${{ github.ref }}"
          tag_name: "${{ github.ref }}"
      - env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        name: Upload linux-bin
        uses: actions/upload-release-asset@v1
        with:
          asset_content_type: application/zip
          asset_name: syconf-linux.zip
          asset_path: syconf-linux.zip
          upload_url: "${{ steps.create_release.outputs.upload_url }}"
      - env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        name: Upload macos-bin
        uses: actions/upload-release-asset@v1
        with:
          asset_content_type: application/zip
          asset_name: syconf-macos.zip
          asset_path: syconf-macos.zip
          upload_url: "${{ steps.create_release.outputs.upload_url }}"
name: build-release
"on":
  push:
    tags: "*"